runtime: python38

entrypoint: gunicorn -b :$PORT main:app

env_variables:
  secret_key: 'G4zbymF@4$5E9Kyk8uZZS_#_hK=LAR'

  database_user: 'root'
  database_password: 'Lmos0MzMm7lksF75'
  database_host: '35.243.167.51'